pub mod automation;
pub mod chord;
pub mod clock;
pub mod envelope;
pub mod euclid;
pub mod inst;
pub mod note;
pub mod pattern;
pub mod random;
pub mod scale;
pub mod sequence;
pub mod synth;

pub use automation::{Automation, AutomationExt, Follow, automation};
pub use chord::{Chord, ChordType};
pub use clock::{Clock, ClockState, clock};
pub use envelope::{Adsr, Stage, adsr};
pub use euclid::Euclid;
pub use note::Note;
pub use pattern::Pattern;
pub use random::{Rng, seeded};
pub use scale::{Scale, ScaleMode};
pub use sequence::{Sequence, StepEvent};
pub use synth::{FilterType, OscShape, PatchError, SubSynth, SynthPatch};
